### ISSUE TITLE
bug in ode_oed_case_1_scipy.py

### ISSUE THREAD

**Issue by notesofdabbler** [KennedyPutraKusumo/pydex#4]
In the [example](https://github.com/KennedyPutraKusumo/pydex/blob/master/examples/ode/ode_oed_case_1_scipy.py), the parameters of simulate function should be the following to run without error
```
simulate(ti_controls, tv_controls, model_parameters, sampling_times)
```

**Comment by KennedyKusumo** [comment]
Thanks, the simulate signatures are now updated to what they should be. 

1. The order for the simulate arguments is now: ti_controls, tv_controls, sampling_times, model_parameters.
2. tv_controls, sampling times are now optional. 
4. if sampling_times is passed, it is a dynamic system. if tv_controls passed, sampling times must be passed in as well. 

Pydex published in PyPI is not up-to-date yet. Just merged in a new pydex with semi-bayesian features. Will update pydex in PyPI.
