### ISSUE TITLE
How to specify a subset of variables are response variables for exerimental design?

### ISSUE THREAD

**Issue by notesofdabbler** [KennedyPutraKusumo/pydex#5]
I was curious on how to specify when we have only a subset of variables in the simulate function that are measured. Do we just output the measured variables in the simulate function?

**Comment by kkuriyan** [comment]
Yes, the simulate function could be set up to only return the measured variable values (for specified controls, parameters and sampling times). Alternatively the measurable_reponses property of the Designer can be set to the indices of the measured responses.
